// Flappy Scream — canvas game, generated by a local LLM
(() => {
  const canvas = document.getElementById("game");
  const ctx = canvas.getContext("2d");
  const W = canvas.width, H = canvas.height;

  const scoreEl = document.getElementById("score");
  const bestEl = document.getElementById("best");
  const overlay = document.getElementById("overlay");
  const msgEl = document.getElementById("msg");
  const startBtn = document.getElementById("start");

  const GROUND = 56;
  const GRAVITY = 1500;        // px/s^2
  const FLAP = -420;           // px/s impulse
  const PIPE_W = 62;
  const GAP = 168;
  const PIPE_SPEED = 170;      // px/s
  const PIPE_EVERY = 1.9;      // seconds

  let bird, pipes, score, best, state, tPrev, spawnT, shake;
  best = Number(localStorage.getItem("flappy-scream-best") || 0);
  bestEl.textContent = best ? "best " + best : "";

  function reset() {
    bird = { x: 96, y: H * 0.42, vy: 0, r: 16, rot: 0, mouth: 0 };
    pipes = [];
    score = 0;
    spawnT = 0;
    shake = 0;
    scoreEl.textContent = "0";
  }

  function flap() {
    if (state !== "play") return;
    bird.vy = FLAP;
    bird.mouth = 0.25; // "scream" animation window
  }

  function start() {
    reset();
    state = "play";
    overlay.classList.add("hidden");
    tPrev = performance.now();
    requestAnimationFrame(loop);
  }

  function gameOver() {
    state = "over";
    if (score > best) {
      best = score;
      localStorage.setItem("flappy-scream-best", String(best));
    }
    bestEl.textContent = "best " + best;
    msgEl.innerHTML = `Skor: <b>${score}</b> · Best: <b>${best}</b><br>Tap / SPASI untuk coba lagi.`;
    startBtn.textContent = "RETRY";
    overlay.classList.remove("hidden");
  }

  function spawnPipe() {
    const minTop = 60, maxTop = H - GROUND - GAP - 60;
    const top = minTop + Math.random() * (maxTop - minTop);
    pipes.push({ x: W, top, passed: false });
  }

  function hit(a, b) {
    // circle vs rect
    const cx = Math.max(b.x, Math.min(a.x, b.x + b.w));
    const cy = Math.max(b.y, Math.min(a.y, b.y + b.h));
    const dx = a.x - cx, dy = a.y - cy;
    return dx * dx + dy * dy < a.r * a.r;
  }

  function update(dt) {
    bird.vy += GRAVITY * dt;
    bird.y += bird.vy * dt;
    bird.rot = Math.max(-0.5, Math.min(1.2, bird.vy / 600));
    bird.mouth = Math.max(0, bird.mouth - dt);

    spawnT += dt;
    if (spawnT >= PIPE_EVERY) { spawnT = 0; spawnPipe(); }

    for (const p of pipes) {
      p.x -= PIPE_SPEED * dt;
      if (!p.passed && p.x + PIPE_W < bird.x) {
        p.passed = true;
        score++;
        scoreEl.textContent = String(score);
      }
      const topRect = { x: p.x, y: 0, w: PIPE_W, h: p.top };
      const botRect = { x: p.x, y: p.top + GAP, w: PIPE_W, h: H - p.top - GAP };
      if (hit(bird, topRect) || hit(bird, botRect)) { shake = 0.35; return gameOver(); }
    }
    pipes = pipes.filter(p => p.x + PIPE_W > -10);

    if (bird.y + bird.r >= H - GROUND) { bird.y = H - GROUND - bird.r; shake = 0.35; return gameOver(); }
    if (bird.y - bird.r < 0) { bird.y = bird.r; bird.vy = 0; }

    shake = Math.max(0, shake - dt);
  }

  function draw() {
    ctx.save();
    if (shake > 0) ctx.translate((Math.random() - .5) * 8, (Math.random() - .5) * 8);
    ctx.clearRect(-10, -10, W + 20, H + 20);

    // stars backdrop
    ctx.fillStyle = "rgba(255,255,255,.08)";
    for (let i = 0; i < 40; i++) {
      const x = (i * 97) % W, y = (i * 53) % (H - GROUND - 40);
      ctx.fillRect(x, y, 2, 2);
    }

    // pipes
    for (const p of pipes) {
      ctx.fillStyle = "#2f9e6e";
      ctx.fillRect(p.x, 0, PIPE_W, p.top);
      ctx.fillRect(p.x, p.top + GAP, PIPE_W, H - p.top - GAP - GROUND);
      ctx.fillStyle = "#268a5e";
      ctx.fillRect(p.x - 4, p.top - 18, PIPE_W + 8, 18);
      ctx.fillRect(p.x - 4, p.top + GAP, PIPE_W + 8, 18);
    }

    // ground
    ctx.fillStyle = "#1c2436";
    ctx.fillRect(0, H - GROUND, W, GROUND);
    ctx.fillStyle = "#232b3d";
    ctx.fillRect(0, H - GROUND, W, 6);

    // bird
    ctx.save();
    ctx.translate(bird.x, bird.y);
    ctx.rotate(bird.rot);
    ctx.fillStyle = "#f0c040";
    ctx.beginPath();
    ctx.arc(0, 0, bird.r, 0, Math.PI * 2);
    ctx.fill();
    // wing
    ctx.fillStyle = "#d9a52e";
    ctx.beginPath();
    ctx.ellipse(-4, 4, 9, 6, -0.4, 0, Math.PI * 2);
    ctx.fill();
    // beak — opens wide when flapping (the "scream")
    const open = bird.mouth > 0 ? 8 : 2;
    ctx.fillStyle = "#e2622b";
    ctx.beginPath();
    ctx.moveTo(bird.r - 2, -3);
    ctx.lineTo(bird.r + 12, -3);
    ctx.lineTo(bird.r + 12, -3 + open);
    ctx.lineTo(bird.r - 2, 2);
    ctx.closePath();
    ctx.fill();
    // eye
    ctx.fillStyle = "#0b0e14";
    ctx.beginPath();
    ctx.arc(6, -5, 3, 0, Math.PI * 2);
    ctx.fill();
    ctx.restore();

    ctx.restore();
  }

  function loop(t) {
    if (state !== "play") { draw(); return; }
    const dt = Math.min(0.033, (t - tPrev) / 1000);
    tPrev = t;
    update(dt);
    draw();
    requestAnimationFrame(loop);
  }

  // input
  startBtn.addEventListener("click", (e) => { e.stopPropagation(); start(); });
  canvas.addEventListener("pointerdown", () => state === "play" ? flap() : start());
  window.addEventListener("keydown", (e) => {
    if (e.code === "Space" || e.code === "ArrowUp") {
      e.preventDefault();
      state === "play" ? flap() : start();
    }
  });

  reset();
  state = "idle";
  draw();
})();
